name: Kotlin Script Test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash

jobs:
  kts-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Kotlin Script on ${{ matrix.os }}
        id: kotlin-script-exec
        uses: ./
        with:
          script: ".github/scripts/script.main.kts"
          compiler-plugin: kotlinx-serialization
          # cache: true

      - name: Print Kotlin install and compiler plugin path
        run: |
          java -version
          echo "Plugin Path       : ${{ steps.kotlin-script-exec.outputs.plugin-path }}"
          echo "Plugin Path (Env) : $PLUGIN_PATH"
          echo "Kotlin Root       : ${{ steps.kotlin-script-exec.outputs.kotlin-root }}"
          echo "Kotlin Root (Env) : $KOTLIN_ROOT"

      - name: List all the Kotlin binaries
        run: |
          cd "${{ steps.kotlin-script-exec.outputs.kotlin-root }}/bin"
          ls -ltrh
